name: Test
on:
  pull_request:
    branches:
      - master

jobs:
  test_with_input:
    runs-on: ubuntu-latest
    name: Test brotli action with input
    steps:
      - name: Check out repo
        uses: actions/checkout@v1

      - name: check the files have not been compressed yet
        run: |
          import sys
          import os
          if os.path.isfile('./test/dirA/test.html.br'):
            sys.exit("Error: Compressed .html file was found before it should have been compressed")
          if os.path.isfile('./test/dirA/test.css.br'):
            sys.exit("Error: Compressed .css file was found before it should have been compressed")
          if os.path.isfile('./test/dirA/test.js.br'):
            sys.exit("Error: Compressed .js file was found before it should have been compressed")
        shell: python

      - name: Test the brotli action step
        id: brotli-test
        uses: charlesworth/brotli-github-action@0.6
        with:
          target-directory: 'test/dirA'

      - name: check the files have now been compressed
        run: |
          import sys
          import os
          if not os.path.isfile('./test/dirA/test.html.br'):
            sys.exit("Error: Compressed .html file was not found")
          if not os.path.isfile('./test/dirA/test.css.br'):
            sys.exit("Error: Compressed .css file was not found")
          if not os.path.isfile('./test/dirA/test.js.br'):
            sys.exit("Error: Compressed .js file was not found")
        shell: python

      - name: check the files from a seperate firectory have not been compressed
        run: |
          import sys
          import os
          if os.path.isfile('./test/dirB/test.html.br'):
            sys.exit("Error: Compressed .html file was not found in a non target directory")
          if os.path.isfile('./test/dirB/test.css.br'):
            sys.exit("Error: Compressed .css file was not found in a non target directory")
          if os.path.isfile('./test/dirB/test.js.br'):
            sys.exit("Error: Compressed .js file was not found in a non target directory")
        shell: python

      - name: check the incorrect file types have not been compressed
        run: |
          import sys
          import os
          if os.path.isfile('./test/dirB/test.txt.br'):
            sys.exit("Error: Compressed .txt file was found when it should not have been compressed")
        shell: python

  test_without_input:
    runs-on: ubuntu-latest
    name: Test brotli action without input
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v1
      - name: get the dir structure
        run: ls -R
      - name: Test the brotli action step
        id: brotli-test
        uses: charlesworth/brotli-github-action@0.6
      - name: get the dir structure
        run: ls -R
