name: Test
on:
  pull_request:
    branches:
      - master

jobs:
  test_with_input:
    runs-on: ubuntu-latest
    name: Test brotli action with input
    steps:
      - name: Check out repo
        uses: actions/checkout@v1

      - name: Check the files have not been compressed yet
        run: |
          import sys
          import os
          for fileType in [".html", ".css", ".js"]:
            if os.path.isfile('./test/dirA/test{}.br'.format(fileType)):
              sys.exit('Error: Compressed {} file was found before it should have been compressed'.format(fileType))
        shell: python

      - name: Test the brotli action step
        id: brotli-test
        uses: charlesworth/brotli-github-action@0.6
        with:
          target-directory: 'test/dirA'

      - name: Check the files have now been compressed
        run: |
          import sys
          import os
          for fileType in [".html", ".css", ".js"]:
            if not os.path.isfile('./test/dirA/test{}.br'.format(fileType)):
              sys.exit('Error: Compressed {} file was not found'.format(fileType))
        shell: python

      - name: Check the files from a seperate firectory have not been compressed
        run: |
          import sys
          import os
          for fileType in [".html", ".css", ".js", ".txt"]:
            if os.path.isfile('./test/dirB/test{}.br'.format(fileType)):
              sys.exit('Error: Compressed {} file was not found in a non target directory'.format(fileType))
        shell: python

      - name: Check the incorrect file types have not been compressed
        run: |
          import sys
          import os
          if os.path.isfile('./test/dirB/test.txt.br'):
            sys.exit("Error: Compressed .txt file was found when it should not have been compressed")
        shell: python

  test_without_input:
    runs-on: ubuntu-latest
    name: Test brotli action without input
    steps:
      - name: Check out repo
        uses: actions/checkout@v1

      - name: Check the files have not been compressed yet
        run: |
          import sys
          import os
          for directory in ["/dirA", "/dirB"]:
            for fileType in [".html", ".css", ".js"]:
              if os.path.isfile('./test{}/test{}.br'.format(directory, fileType)):
                sys.exit('Error: Compressed {}/test{} file was found before it should have been compressed'.format(directory, fileType))
        shell: python

      - name: Test the brotli action step
        id: brotli-test
        uses: charlesworth/brotli-github-action@0.6

      - name: Check the files have now been compressed
        run: |
          import sys
          import os
          for directory in ["/dirA", "/dirB"]:
            for fileType in [".html", ".css", ".js"]:
              if not os.path.isfile('./test{}/test{}.br'.format(directory, fileType)):
                sys.exit('Error: Compressed {}/test{} file was not found'.format(directory, fileType))
        shell: python

      - name: Check the incorrect file types have not been compressed
        run: |
          import sys
          import os
          for directory in ["/dirA", "/dirB"]:
            if os.path.isfile('./test{}/test.txt.br'.format(directory)):
              sys.exit('Error: Compressed {}/test.txt file was found when it should not have been compressed'.format(directory))
        shell: python
